#server:
#  port: 8082
#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/dsa
#    username: admin
#    password: Sriban@123
#    driver-class-name: com.mysql.cj.jdbc.Driver
#  jpa:
#    hibernate:
#      ddl-auto: update
#    properties:
#      hibernate:
#        show_sql: true
#        format_sql: false
#  batch:
#    jdbc:
#      initialize-schema: EMBEDDED
#    job:
#      enabled: false
#
#eureka:
#  client:
#    register-with-eureka: true
#    fetch-registry: true

spring:
  application:
    name: kafka-consumer-service
  config:
    import: 'optional:configserver:${config-server:http://192.168.1.17:9090/}'
  profiles:
    active: '${active-profile:dev}'
  cloud:
    config:
      uri: '${config-server:http://192.168.1.17:9090/}'
      name: app-server,kafka-consumer-service

#  kafka:
#    consumer:
#      bootstrap-servers: 192.168.1.7:9092
#      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      group-id: client_group
